In [2]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Things you should automatically know and have memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [7]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)
X.shape

(1, 10, 3)

In [8]:
# Make an RNN
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [9]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

[[0.26625028 0.19515018]]


In [10]:
# See if we can replicate this output
# Get the weights first
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [11]:
# See what's returned
model.layers[1].get_weights()

[array([[-0.4859923 , -0.7763652 , -0.04761058, -0.53987074,  0.67142326],
        [-0.74768275,  0.5861774 , -0.27204812,  0.5199482 ,  0.48903757],
        [ 0.717066  ,  0.02335185, -0.66123927,  0.07800251, -0.8059281 ]],
       dtype=float32),
 array([[-0.00489271,  0.42348439, -0.51715976,  0.44094232, -0.5989596 ],
        [-0.41394892, -0.77844673,  0.03922731,  0.23866642, -0.40517476],
        [ 0.47346178, -0.0209707 ,  0.3751601 , -0.4382652 , -0.6652614 ],
        [ 0.77367324, -0.42023206, -0.282708  ,  0.33246422,  0.18541436],
        [-0.07672035, -0.19402833, -0.7143795 , -0.66783184, -0.01138569]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [12]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [14]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [15]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[0.26625025 0.19515011]
